version: '3.9'

services:
  mysql:
    image: mysql:5.7
    container_name: doji-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: doji
      MYSQL_DATABASE: doji
    ports:
      - "3307:3306"

  mongo:
    image: mongo:latest
    container_name: doji-mongo
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - "./volume/mongo:/data/db"
