version: '3.9'

services:
  mysql:
    image: mysql:5.7
    container_name: doji-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"

  mongo:
    image: mongo:latest
    container_name: doji-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
